baseURL = 'https://erk.quest/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'erkquest'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'