baseURL = 'https://erk.quest/'
languageCode = 'en-us'
title = 'Erk.quest'
theme = 'erkquest'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
[markup.goldmark.renderHooks.image]
  enableDefault = true
[markup.goldmark.renderHooks.link]
  enableDefault = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'