baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Erk.Quest'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Quests'
    pageRef = '/quests'
    weight = 20

  [[menus.main]]
    name = 'Games'
    pageRef = '/games'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
